name: MongoDB Connection

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up MongoDB environment
      uses: mongodb/setup-mongodb@v1
      with:
        mongodb-version: '4.4' # Specify the desired MongoDB version

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
